sudo: required
language: python
python:
- 3.6
services:
- docker
script:
- true # TODO: write some tests
before_deploy:
- docker build -t aws-lambda-pdf-optimizer .
- docker run --rm -v "$PWD":/var/task aws-lambda-pdf-optimizer
deploy:
  provider: releases
  api_key:
    secure: ZRKZrQvj+0JqOJC95/a2i5Jt+TE4JCU7cmm5i9eTFz0RHPtcKUpu9ng3VulSTaV3mkZPeoyelTnQhFlxQpNY9r75Yoijs0hkd1tjJeoV9Ul3NxcoWiDNxJ61v1S+l7VNu1X2dBO1FPJ3YbFselcho6pCV54Z8XiEfwXqvxgfczTuDG4bIhfq7ZzS7zmKkDK/ZffYOnBxwqZE9mm/yY/tePdfHXkxudBnCGsxdiML43DFKUzZoOtZup+utyQ983EjxXYwWgVkvHmAb9gPUjSDyT5UGs80Mvkju9QKn2bFeW0n+j27bd9JyKpzAD+VIse9OLm81A3hejlL+Go9pSNGFwou4BTq6Ul5W8TXKKxmSolpPDJTXAol/YAUNXYj4p5iu2ZCP98gI0eA8H64DESah+PDF615O+YTtbIVD19uxuP++SZaEUYr9J84cD3yh4QKHGxOHSsoWFkquqWGbsUJRT0MzxpMpeWuXu5Z8AyWyhlGtRtkOV/Seekw/S5/rN5NI8l4bRdmcaAaTnvSDxa/QtrcrWSwM+yTSxHL99VttXPQ9ApLPjpJOK5/SVDmdM85MAUOBhZoPwWXJNt2bgg+61jy29zsOnfYtc0FpoG3rWXu7uP9fPlvSY+kiT/gh2OR7FWsKxuXSdmPimBSiYVKDFxnehmso6dTy4Tk0CqV+5E=
  file: deploy_package.zip
  skip_cleanup: true
  on:
    tags: true
    repo: blooper05/aws-lambda-pdf-optimizer
